### ISSUE TITLE
Ja está trabalhando na aréa?

### ISSUE THREAD

**Issue by richhh7g** [AlcivanLucas/Faltometro#1]

**Comment by AlcivanLucas** [comment]
Estou atualmente fazendo um projeto beneficente financiado pelo pela faculdade e prefeitura do Piauí o ConcretoSmart, mas ainda não consegui um estágio, ainda kkkkkk, por enquanto só nos freelancers e projetos pessoas mesmo

**Comment by richhh7g** [comment]
Que massa, ta com a agenda cheia hoje?

**Comment by AlcivanLucas** [comment]
acabei de terminar uma call com a equipe do porjeto, chama lá no linkedin: https://www.linkedin.com/in/alcivan-lucas

**Comment by richhh7g** [comment]
Linkdin e um dos ultimos lugares que tu pode me encontrar kkkk, topa fazer uma call as 15h no GoogleMeet?

**Comment by AlcivanLucas** [comment]
qual rede social a gente pode conversar melhor?

**Comment by AlcivanLucas** [comment]
tô tentando largar meu vicio do Orkut rsrs, troquei pelo linkedin

**Comment by richhh7g** [comment]
me chama no telegram [richhh7g](https://t.me/richhh7g) ou pelo meu email richhh7g@protonmail.com

**Comment by AlcivanLucas** [comment]
mandei o email!, não criei um telegram ainda, minhas redes sociais estão defasadas rsrs

**Comment by richhh7g** [comment]
Boa respondi la.
